# Configuration for CI test_llama.sh - stories110M with MPS backend

base:
  model_class: "stories110m"

model:
  dtype_override: "fp32"
  use_kv_cache: true
  enable_dynamic_shape: false

export:
  max_seq_length: 128
  max_context_length: 128

backend:
  mps:
    enabled: true

debug:
  verbose: true