# Configuration for CI test_llama.sh - stories110M with XNNPACK quantization
# Used when XNNPACK=ON, CUSTOM=ON, QE=ON modes are enabled

base:
  model_class: "stories110m"

model:
  dtype_override: "fp32"
  use_kv_cache: true
  use_sdpa_with_kv_cache: true

export:
  max_seq_length: 128
  max_context_length: 128

quantization:
  qmode: "8da4w"
  group_size: 128
  embedding_quantize: "8,1024"

backend:
  xnnpack:
    enabled: true
    extended_ops: true

debug:
  verbose: false