# Configuration for stories110M with TorchAO lowbit quantization
# Used in CI test_llama_torchao_lowbit.sh

base:
  model_class: "stories110m"

model:
  dtype_override: "fp32"
  use_kv_cache: true
  use_sdpa_with_kv_cache: true

export:
  max_seq_length: 128
  max_context_length: 128

quantization:
  qmode: "torchao:8da3w"  # QLINEAR_BITWIDTH=3
  group_size: 128        # QLINEAR_GROUP_SIZE=128
  embedding_quantize: "4,32"  # QEMBEDDING_BITWIDTH=4, QEMBEDDING_GROUP_SIZE=32

backend:
  xnnpack:
    enabled: false

debug:
  verbose: false