# Configuration for XNNPACK + custom + quantization
# Common pattern used in CI test_llama.sh

base:
  model_class: "stories110m"

model:
  dtype_override: "fp32"
  use_kv_cache: true
  use_sdpa_with_kv_cache: true

export:
  max_seq_length: 128
  max_context_length: 128

quantization:
  qmode: "8da4w"
  group_size: 128
  embedding_quantize: "8,1024"  # Default from test_llama.sh QE mode

backend:
  xnnpack:
    enabled: true
    extended_ops: true

debug:
  verbose: false